package com.capystick.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

private data class PaletteColorSet(
    val lightScheme: ColorScheme,
    val darkScheme: ColorScheme,
    val lightPreview: PalettePreview,
    val darkPreview: PalettePreview,
)

@Immutable
data class PalettePreview(
    val primary: Color,
    val secondary: Color,
    val tertiary: Color,
    val surface: Color,
)

private val defaultLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val defaultDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val forestLightScheme = lightColorScheme(
    primary = Color(0xFF2D6A4F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFAEE9C8),
    onPrimaryContainer = Color(0xFF0D2017),
    secondary = Color(0xFF496553),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCBECD4),
    onSecondaryContainer = Color(0xFF112018),
    tertiary = Color(0xFF596030),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDDE6A8),
    onTertiaryContainer = Color(0xFF1A1E00),
    background = Color(0xFFF4FBF4),
    onBackground = Color(0xFF161D18),
    surface = Color(0xFFF4FBF4),
    onSurface = Color(0xFF161D18),
    surfaceVariant = Color(0xFFDCE5DA),
    onSurfaceVariant = Color(0xFF404942),
    outline = Color(0xFF707971),
    outlineVariant = Color(0xFFC0C9BE),
    inverseSurface = Color(0xFF2B322D),
    inverseOnSurface = Color(0xFFECF2EC),
    inversePrimary = Color(0xFF93DCAE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEEF5EF),
    surfaceContainer = Color(0xFFE8EFE8),
    surfaceContainerHigh = Color(0xFFE2EAE2),
    surfaceContainerHighest = Color(0xFFDDE4DD),
)

private val forestDarkScheme = darkColorScheme(
    primary = Color(0xFF92D5B0),
    onPrimary = Color(0xFF003822),
    primaryContainer = Color(0xFF165139),
    onPrimaryContainer = Color(0xFFAEE9C8),
    secondary = Color(0xFFAFCFBA),
    onSecondary = Color(0xFF1C3526),
    secondaryContainer = Color(0xFF334C3D),
    onSecondaryContainer = Color(0xFFCBECD4),
    tertiary = Color(0xFFC1CA8E),
    onTertiary = Color(0xFF2C3408),
    tertiaryContainer = Color(0xFF42491D),
    onTertiaryContainer = Color(0xFFDDE6A8),
    background = Color(0xFF0E1511),
    onBackground = Color(0xFFDDE4DD),
    surface = Color(0xFF0E1511),
    onSurface = Color(0xFFDDE4DD),
    surfaceVariant = Color(0xFF404942),
    onSurfaceVariant = Color(0xFFC0C9BE),
    outline = Color(0xFF8A938B),
    outlineVariant = Color(0xFF404942),
    inverseSurface = Color(0xFFDDE4DD),
    inverseOnSurface = Color(0xFF2B322D),
    inversePrimary = Color(0xFF2D6A4F),
    surfaceContainerLowest = Color(0xFF09100C),
    surfaceContainerLow = Color(0xFF161D18),
    surfaceContainer = Color(0xFF1A211C),
    surfaceContainerHigh = Color(0xFF252C27),
    surfaceContainerHighest = Color(0xFF303732),
)

private val oceanLightScheme = lightColorScheme(
    primary = Color(0xFF0A5FA8),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD2E4FF),
    onPrimaryContainer = Color(0xFF001C38),
    secondary = Color(0xFF3A6689),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD0E4F8),
    onSecondaryContainer = Color(0xFF081E2E),
    tertiary = Color(0xFF7B5700),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDEA6),
    onTertiaryContainer = Color(0xFF261900),
    background = Color(0xFFF7F9FF),
    onBackground = Color(0xFF161C23),
    surface = Color(0xFFF7F9FF),
    onSurface = Color(0xFF161C23),
    surfaceVariant = Color(0xFFDDE3EA),
    onSurfaceVariant = Color(0xFF41474D),
    outline = Color(0xFF71787E),
    outlineVariant = Color(0xFFC1C7CE),
    inverseSurface = Color(0xFF2B3138),
    inverseOnSurface = Color(0xFFEDF1F8),
    inversePrimary = Color(0xFFA3C9FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF0F4FB),
    surfaceContainer = Color(0xFFEAEEF5),
    surfaceContainerHigh = Color(0xFFE4E8F0),
    surfaceContainerHighest = Color(0xFFDEE3EA),
)

private val oceanDarkScheme = darkColorScheme(
    primary = Color(0xFFA3C9FF),
    onPrimary = Color(0xFF00315B),
    primaryContainer = Color(0xFF004881),
    onPrimaryContainer = Color(0xFFD2E4FF),
    secondary = Color(0xFF9DC8EE),
    onSecondary = Color(0xFF03304F),
    secondaryContainer = Color(0xFF224C6F),
    onSecondaryContainer = Color(0xFFD0E4F8),
    tertiary = Color(0xFFF2BE48),
    onTertiary = Color(0xFF402D00),
    tertiaryContainer = Color(0xFF5C4100),
    onTertiaryContainer = Color(0xFFFFDEA6),
    background = Color(0xFF0F141B),
    onBackground = Color(0xFFDEE3EA),
    surface = Color(0xFF0F141B),
    onSurface = Color(0xFFDEE3EA),
    surfaceVariant = Color(0xFF41474D),
    onSurfaceVariant = Color(0xFFC1C7CE),
    outline = Color(0xFF8B9198),
    outlineVariant = Color(0xFF41474D),
    inverseSurface = Color(0xFFDEE3EA),
    inverseOnSurface = Color(0xFF2B3138),
    inversePrimary = Color(0xFF0A5FA8),
    surfaceContainerLowest = Color(0xFF090E14),
    surfaceContainerLow = Color(0xFF171C23),
    surfaceContainer = Color(0xFF1B2027),
    surfaceContainerHigh = Color(0xFF252B33),
    surfaceContainerHighest = Color(0xFF30363D),
)

private val yellowLightScheme = lightColorScheme(
    primary = yellowPrimaryLight,
    onPrimary = yellowOnPrimaryLight,
    primaryContainer = yellowPrimaryContainerLight,
    onPrimaryContainer = yellowOnPrimaryContainerLight,
    secondary = yellowSecondaryLight,
    onSecondary = yellowOnSecondaryLight,
    secondaryContainer = yellowSecondaryContainerLight,
    onSecondaryContainer = yellowOnSecondaryContainerLight,
    tertiary = yellowTertiaryLight,
    onTertiary = yellowOnTertiaryLight,
    tertiaryContainer = yellowTertiaryContainerLight,
    onTertiaryContainer = yellowOnTertiaryContainerLight,
    error = yellowErrorLight,
    onError = yellowOnErrorLight,
    errorContainer = yellowErrorContainerLight,
    onErrorContainer = yellowOnErrorContainerLight,
    background = yellowBackgroundLight,
    onBackground = yellowOnBackgroundLight,
    surface = yellowSurfaceLight,
    onSurface = yellowOnSurfaceLight,
    surfaceVariant = yellowSurfaceVariantLight,
    onSurfaceVariant = yellowOnSurfaceVariantLight,
    outline = yellowOutlineLight,
    outlineVariant = yellowOutlineVariantLight,
    scrim = yellowScrimLight,
    inverseSurface = yellowInverseSurfaceLight,
    inverseOnSurface = yellowInverseOnSurfaceLight,
    inversePrimary = yellowInversePrimaryLight,
    surfaceDim = yellowSurfaceDimLight,
    surfaceBright = yellowSurfaceBrightLight,
    surfaceContainerLowest = yellowSurfaceContainerLowestLight,
    surfaceContainerLow = yellowSurfaceContainerLowLight,
    surfaceContainer = yellowSurfaceContainerLight,
    surfaceContainerHigh = yellowSurfaceContainerHighLight,
    surfaceContainerHighest = yellowSurfaceContainerHighestLight,
)

private val yellowDarkScheme = darkColorScheme(
    primary = yellowPrimaryDark,
    onPrimary = yellowOnPrimaryDark,
    primaryContainer = yellowPrimaryContainerDark,
    onPrimaryContainer = yellowOnPrimaryContainerDark,
    secondary = yellowSecondaryDark,
    onSecondary = yellowOnSecondaryDark,
    secondaryContainer = yellowSecondaryContainerDark,
    onSecondaryContainer = yellowOnSecondaryContainerDark,
    tertiary = yellowTertiaryDark,
    onTertiary = yellowOnTertiaryDark,
    tertiaryContainer = yellowTertiaryContainerDark,
    onTertiaryContainer = yellowOnTertiaryContainerDark,
    error = yellowErrorDark,
    onError = yellowOnErrorDark,
    errorContainer = yellowErrorContainerDark,
    onErrorContainer = yellowOnErrorContainerDark,
    background = yellowBackgroundDark,
    onBackground = yellowOnBackgroundDark,
    surface = yellowSurfaceDark,
    onSurface = yellowOnSurfaceDark,
    surfaceVariant = yellowSurfaceVariantDark,
    onSurfaceVariant = yellowOnSurfaceVariantDark,
    outline = yellowOutlineDark,
    outlineVariant = yellowOutlineVariantDark,
    scrim = yellowScrimDark,
    inverseSurface = yellowInverseSurfaceDark,
    inverseOnSurface = yellowInverseOnSurfaceDark,
    inversePrimary = yellowInversePrimaryDark,
    surfaceDim = yellowSurfaceDimDark,
    surfaceBright = yellowSurfaceBrightDark,
    surfaceContainerLowest = yellowSurfaceContainerLowestDark,
    surfaceContainerLow = yellowSurfaceContainerLowDark,
    surfaceContainer = yellowSurfaceContainerDark,
    surfaceContainerHigh = yellowSurfaceContainerHighDark,
    surfaceContainerHighest = yellowSurfaceContainerHighestDark,
)

private val roseLightScheme = lightColorScheme(
    primary = rosePrimaryLight,
    onPrimary = roseOnPrimaryLight,
    primaryContainer = rosePrimaryContainerLight,
    onPrimaryContainer = roseOnPrimaryContainerLight,
    secondary = roseSecondaryLight,
    onSecondary = roseOnSecondaryLight,
    secondaryContainer = roseSecondaryContainerLight,
    onSecondaryContainer = roseOnSecondaryContainerLight,
    tertiary = roseTertiaryLight,
    onTertiary = roseOnTertiaryLight,
    tertiaryContainer = roseTertiaryContainerLight,
    onTertiaryContainer = roseOnTertiaryContainerLight,
    error = roseErrorLight,
    onError = roseOnErrorLight,
    errorContainer = roseErrorContainerLight,
    onErrorContainer = roseOnErrorContainerLight,
    background = roseBackgroundLight,
    onBackground = roseOnBackgroundLight,
    surface = roseSurfaceLight,
    onSurface = roseOnSurfaceLight,
    surfaceVariant = roseSurfaceVariantLight,
    onSurfaceVariant = roseOnSurfaceVariantLight,
    outline = roseOutlineLight,
    outlineVariant = roseOutlineVariantLight,
    scrim = roseScrimLight,
    inverseSurface = roseInverseSurfaceLight,
    inverseOnSurface = roseInverseOnSurfaceLight,
    inversePrimary = roseInversePrimaryLight,
    surfaceDim = roseSurfaceDimLight,
    surfaceBright = roseSurfaceBrightLight,
    surfaceContainerLowest = roseSurfaceContainerLowestLight,
    surfaceContainerLow = roseSurfaceContainerLowLight,
    surfaceContainer = roseSurfaceContainerLight,
    surfaceContainerHigh = roseSurfaceContainerHighLight,
    surfaceContainerHighest = roseSurfaceContainerHighestLight,
)

private val roseDarkScheme = darkColorScheme(
    primary = rosePrimaryDark,
    onPrimary = roseOnPrimaryDark,
    primaryContainer = rosePrimaryContainerDark,
    onPrimaryContainer = roseOnPrimaryContainerDark,
    secondary = roseSecondaryDark,
    onSecondary = roseOnSecondaryDark,
    secondaryContainer = roseSecondaryContainerDark,
    onSecondaryContainer = roseOnSecondaryContainerDark,
    tertiary = roseTertiaryDark,
    onTertiary = roseOnTertiaryDark,
    tertiaryContainer = roseTertiaryContainerDark,
    onTertiaryContainer = roseOnTertiaryContainerDark,
    error = roseErrorDark,
    onError = roseOnErrorDark,
    errorContainer = roseErrorContainerDark,
    onErrorContainer = roseOnErrorContainerDark,
    background = roseBackgroundDark,
    onBackground = roseOnBackgroundDark,
    surface = roseSurfaceDark,
    onSurface = roseOnSurfaceDark,
    surfaceVariant = roseSurfaceVariantDark,
    onSurfaceVariant = roseOnSurfaceVariantDark,
    outline = roseOutlineDark,
    outlineVariant = roseOutlineVariantDark,
    scrim = roseScrimDark,
    inverseSurface = roseInverseSurfaceDark,
    inverseOnSurface = roseInverseOnSurfaceDark,
    inversePrimary = roseInversePrimaryDark,
    surfaceDim = roseSurfaceDimDark,
    surfaceBright = roseSurfaceBrightDark,
    surfaceContainerLowest = roseSurfaceContainerLowestDark,
    surfaceContainerLow = roseSurfaceContainerLowDark,
    surfaceContainer = roseSurfaceContainerDark,
    surfaceContainerHigh = roseSurfaceContainerHighDark,
    surfaceContainerHighest = roseSurfaceContainerHighestDark,
)

private val redLightScheme = lightColorScheme(
    primary = redPrimaryLight,
    onPrimary = redOnPrimaryLight,
    primaryContainer = redPrimaryContainerLight,
    onPrimaryContainer = redOnPrimaryContainerLight,
    secondary = redSecondaryLight,
    onSecondary = redOnSecondaryLight,
    secondaryContainer = redSecondaryContainerLight,
    onSecondaryContainer = redOnSecondaryContainerLight,
    tertiary = redTertiaryLight,
    onTertiary = redOnTertiaryLight,
    tertiaryContainer = redTertiaryContainerLight,
    onTertiaryContainer = redOnTertiaryContainerLight,
    error = redErrorLight,
    onError = redOnErrorLight,
    errorContainer = redErrorContainerLight,
    onErrorContainer = redOnErrorContainerLight,
    background = redBackgroundLight,
    onBackground = redOnBackgroundLight,
    surface = redSurfaceLight,
    onSurface = redOnSurfaceLight,
    surfaceVariant = redSurfaceVariantLight,
    onSurfaceVariant = redOnSurfaceVariantLight,
    outline = redOutlineLight,
    outlineVariant = redOutlineVariantLight,
    scrim = redScrimLight,
    inverseSurface = redInverseSurfaceLight,
    inverseOnSurface = redInverseOnSurfaceLight,
    inversePrimary = redInversePrimaryLight,
    surfaceDim = redSurfaceDimLight,
    surfaceBright = redSurfaceBrightLight,
    surfaceContainerLowest = redSurfaceContainerLowestLight,
    surfaceContainerLow = redSurfaceContainerLowLight,
    surfaceContainer = redSurfaceContainerLight,
    surfaceContainerHigh = redSurfaceContainerHighLight,
    surfaceContainerHighest = redSurfaceContainerHighestLight,
)

private val redDarkScheme = darkColorScheme(
    primary = redPrimaryDark,
    onPrimary = redOnPrimaryDark,
    primaryContainer = redPrimaryContainerDark,
    onPrimaryContainer = redOnPrimaryContainerDark,
    secondary = redSecondaryDark,
    onSecondary = redOnSecondaryDark,
    secondaryContainer = redSecondaryContainerDark,
    onSecondaryContainer = redOnSecondaryContainerDark,
    tertiary = redTertiaryDark,
    onTertiary = redOnTertiaryDark,
    tertiaryContainer = redTertiaryContainerDark,
    onTertiaryContainer = redOnTertiaryContainerDark,
    error = redErrorDark,
    onError = redOnErrorDark,
    errorContainer = redErrorContainerDark,
    onErrorContainer = redOnErrorContainerDark,
    background = redBackgroundDark,
    onBackground = redOnBackgroundDark,
    surface = redSurfaceDark,
    onSurface = redOnSurfaceDark,
    surfaceVariant = redSurfaceVariantDark,
    onSurfaceVariant = redOnSurfaceVariantDark,
    outline = redOutlineDark,
    outlineVariant = redOutlineVariantDark,
    scrim = redScrimDark,
    inverseSurface = redInverseSurfaceDark,
    inverseOnSurface = redInverseOnSurfaceDark,
    inversePrimary = redInversePrimaryDark,
    surfaceDim = redSurfaceDimDark,
    surfaceBright = redSurfaceBrightDark,
    surfaceContainerLowest = redSurfaceContainerLowestDark,
    surfaceContainerLow = redSurfaceContainerLowDark,
    surfaceContainer = redSurfaceContainerDark,
    surfaceContainerHigh = redSurfaceContainerHighDark,
    surfaceContainerHighest = redSurfaceContainerHighestDark,
)

private val paletteCatalog = mapOf(
    ColorPaletteOption.DEFAULT to PaletteColorSet(
        lightScheme = defaultLightScheme,
        darkScheme = defaultDarkScheme,
        lightPreview = PalettePreview(
            primary = primaryLight,
            secondary = secondaryLight,
            tertiary = tertiaryLight,
            surface = surfaceContainerHighLight,
        ),
        darkPreview = PalettePreview(
            primary = primaryDark,
            secondary = secondaryDark,
            tertiary = tertiaryDark,
            surface = surfaceContainerHighDark,
        ),
    ),
    ColorPaletteOption.FOREST to PaletteColorSet(
        lightScheme = forestLightScheme,
        darkScheme = forestDarkScheme,
        lightPreview = PalettePreview(
            primary = Color(0xFF2D6A4F),
            secondary = Color(0xFF496553),
            tertiary = Color(0xFF596030),
            surface = Color(0xFFE8EFE8),
        ),
        darkPreview = PalettePreview(
            primary = Color(0xFF92D5B0),
            secondary = Color(0xFFAFCFBA),
            tertiary = Color(0xFFC1CA8E),
            surface = Color(0xFF252C27),
        ),
    ),
    ColorPaletteOption.OCEAN to PaletteColorSet(
        lightScheme = oceanLightScheme,
        darkScheme = oceanDarkScheme,
        lightPreview = PalettePreview(
            primary = Color(0xFF0A5FA8),
            secondary = Color(0xFF3A6689),
            tertiary = Color(0xFF7B5700),
            surface = Color(0xFFEAEEF5),
        ),
        darkPreview = PalettePreview(
            primary = Color(0xFFA3C9FF),
            secondary = Color(0xFF9DC8EE),
            tertiary = Color(0xFFF2BE48),
            surface = Color(0xFF252B33),
        ),
    ),
    ColorPaletteOption.YELLOW to PaletteColorSet(
        lightScheme = yellowLightScheme,
        darkScheme = yellowDarkScheme,
        lightPreview = PalettePreview(
            primary = yellowPrimaryLight,
            secondary = yellowSecondaryLight,
            tertiary = yellowTertiaryLight,
            surface = yellowSurfaceContainerHighLight,
        ),
        darkPreview = PalettePreview(
            primary = yellowPrimaryDark,
            secondary = yellowSecondaryDark,
            tertiary = yellowTertiaryDark,
            surface = yellowSurfaceContainerHighDark,
        ),
    ),
    ColorPaletteOption.ROSE to PaletteColorSet(
        lightScheme = roseLightScheme,
        darkScheme = roseDarkScheme,
        lightPreview = PalettePreview(
            primary = rosePrimaryLight,
            secondary = roseSecondaryLight,
            tertiary = roseTertiaryLight,
            surface = roseSurfaceContainerHighLight,
        ),
        darkPreview = PalettePreview(
            primary = rosePrimaryDark,
            secondary = roseSecondaryDark,
            tertiary = roseTertiaryDark,
            surface = roseSurfaceContainerHighDark,
        ),
    ),
    ColorPaletteOption.RED to PaletteColorSet(
        lightScheme = redLightScheme,
        darkScheme = redDarkScheme,
        lightPreview = PalettePreview(
            primary = redPrimaryLight,
            secondary = redSecondaryLight,
            tertiary = redTertiaryLight,
            surface = redSurfaceContainerHighLight,
        ),
        darkPreview = PalettePreview(
            primary = redPrimaryDark,
            secondary = redSecondaryDark,
            tertiary = redTertiaryDark,
            surface = redSurfaceContainerHighDark,
        ),
    ),
)

/*
fun palettePreview(
    option: ColorPaletteOption,
    isDark: Boolean,
): PalettePreview {
    val palette = paletteCatalog[option] ?: paletteCatalog.getValue(ColorPaletteOption.DEFAULT)
    return if (isDark) palette.darkPreview else palette.lightPreview
}
 */

fun resolvePaletteColorScheme(
    paletteOption: ColorPaletteOption,
    isDark: Boolean,
): ColorScheme {
    val palette = paletteCatalog[paletteOption] ?: paletteCatalog.getValue(ColorPaletteOption.DEFAULT)
    return if (isDark) palette.darkScheme else palette.lightScheme
}
